config/routes.rb
Rails.application.routes.draw do
 
   resources :patients do
    resources :physicians
    resources :appointments
   end
   
   resources :physicians do
    resources :patients
    resources :appointments
   end
   
   resources :emailtemplates     
   resources :home_page
   
   get 'emailtemplates/index' => 'emailtemplates#index'
  devise_for :users

   root 'home_page#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    belongs_to :patient
    belongs_to :physician
    
    validates :start_date , presence: :true
    validates :end_date , presence: :true
    validates :physician_id , presence: :true
end

app/models/emailtemplate.rb
class Emailtemplate < ActiveRecord::Base
   validates :key , presence: true
   validates :subject , presence: true
   validates :body , presence: true 
end

app/models/patient.rb
class Patient < ActiveRecord::Base
    has_many :appointments
    has_many :physicians , through: :appointments
    
    validates :patient_name , presence: :true
    validates :age , presence: :true
    validates :telephone_number , presence: :true
end

app/models/physician.rb
class Physician < ActiveRecord::Base
    has_many :appointments
    has_many :patients , through: :appointments
    
    validates :physician_name , presence: :true
    validates :telephone_number , presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
require 'date'
class AppointmentsController < ApplicationController

def create
    @patient = Patient.find(params[:patient_id])
    physician_id = params[:physicians]
    
    #start_date = DateTime.strptime(params.require(:appointment).permit(:start_date) , "%Y-%d-%m")
    #end_date = DateTime.new(params.require(:appointment).permit(:end_date) , "%Y-%d-%m")
    
    start_date = DateTime.now
    end_date = DateTime.now
  
    @patient.appointments.create(start_date: start_date , end_date:  end_date , physician_id: physician_id) 
     if(@patient.save)
      redirect_to @patient
      else
        render 'patients/new'
    end
end

def destroy
    @appointment = Appointment.find(params[:id])
    @patient = @appointment.patient
    @appointment.destroy
    redirect_to @patient
end

end

app/controllers/emailtemplates_controller.rb
class EmailtemplatesController < ApplicationController
  
  def new
    @emailtemplate = Emailtemplate.new
  end
  
  def create
   @emailtemplate = Emailtemplate.new(params.require(:emailtemplate).permit(:key, :subject,:body) )
  
   if(@emailtemplate.save)
     UserMailer.welcome_email(@emailtemplate).deliver_now
     redirect_to emailtemplates_path(@emailtemplate)  
   else
     render 'new'
   end
   
  end
  
  def show
    @emailtemplate = Emailtemplate.find(params[:id])
  end
  
  
  def index
    @emailtemplates = Emailtemplate.all
  end
  
  def edit
    @emailtemplate = Emailtemplate.find(params[:id])
  end
  
  def update
    @emailtemplate = Emailtemplate.find(params[:id])
    @emailtemplate.key = params.require(:emailtemplate)[:key]
    @emailtemplate.subject = params.require(:emailtemplate)[:subject]
    @emailtemplate.body = params.require(:emailtemplate)[:body]
    if(@emailtemplate.save) 
       redirect_to @emailtemplate
       else
        render 'edit'      
    end
  end
  
  
  def destroy
    @emailtemplate = Emailtemplate.find(params[:id])
    if(@emailtemplate.destroy)
        redirect_to emailtemplates_path
        else
        render 'show'
    end
  end
  
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

def new
    @patient = Patient.new
end

def create
    @patient = Patient.new(params.require(:patient).permit(:patient_name , :age , :telephone_number))
    
    if(@patient.save)
        redirect_to @patient
        else
            render 'new'
    end
end

def show
    @patient = Patient.find(params[:id])
    @physicians =  Physician.all
end 

def index 
    @allpatients = Patient.all
end

def edit
    @patient = Patient.find(params[:id])
end

def update
    @patient = Patient.find(params[:id])
    @patient.update(params.require(:patient).permit(:patient_name , :age , :telephone_number))
    
    if(@patient.save)
        redirect_to @patient
        else 
            render 'edit'
    end
    
end 

def destroy
    @patient = Patient.find(params[:id])
    if(@patient.destroy)
        redirect_to patients_path
        else
            render 'show'
    end
      
end




end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController


def new
    @physician = Physician.new
end

def create
    @physician = Physician.new(params.require(:physician).permit(:physician_name , :telephone_number))
    
    if(@physician.save)
        redirect_to @physician
        else
            render 'new'
    end
end

def show
    @physician = Physician.find(params[:id])
end 

def index 
    @allphysicians = Physician.all
end

def edit
    @physician = Physician.find(params[:id])
end

def update
    @physician = Physician.find(params[:id])
    @physician.update(params.require(:physician).permit(:physician_name , :telephone_number))
    
    if(@physician.save)
        redirect_to @physician
        else 
            render 'edit'
    end
    
end 

def destroy
    @physician = Physician.find(params[:id])
    if(@physician.destroy)
        redirect_to physicians_path
        else
            render 'show'
    end
      
end



end

app/views/emailtemplates/_form.html.erb
<%= form_for @emailtemplate do |f| %>
  <div class="form-group">
    <label for="exampleInputEmail1">
       Email:
    </label>
    
    <%= f.text_field :key , class:'form-control',placeholder:'email' %>
    
  </div>
  
  <div class="form-group">
    <label for="exampleInputEmail1">
        User name:
    </label>
    
    <%= f.text_field :subject , class:'form-control',placeholder:'user name' %>
  
  </div>
  
    <div class="form-group">
    <label for="exampleInputEmail1">
        <%= f.label :body %>
    </label>
    
    <%= f.text_area :body , class:'form-control',placeholder:'body' %>
  
  </div>
  
     <%= f.submit 'Submit' , class: 'btn btn-default'%>
<% end %>

app/views/emailtemplates/edit.html.erb
 <div class='container' style="margin:100px">
      <div class="row">
<h2> Email Template ( <%= @emailtemplate.key %>) </h2>


<%= render 'form' %>

app/views/emailtemplates/index.html.erb
<div class='container' style="margin:100px">
<div style='margin-left:1000px!important'>
<%= link_to 'Add New + ' , new_emailtemplate_path %> 
<br\>
</div>
<% @emailtemplates.each do |emailtemplate| %> 
Email Template (  <%= link_to emailtemplate.key , emailtemplate %> ) <br/>
User name: <%= emailtemplate.subject %><br/>
Body: <%= emailtemplate.body %><br/>
  <%= link_to 'edit' ,  edit_emailtemplate_path(emailtemplate.id) %>
    <%= link_to 'destroy', emailtemplate_path(emailtemplate.id) , method: :delete , data: {confirm: "are you sure you want to delete ?"} %>
<hr/>
<%end%>

app/views/emailtemplates/new.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> New Email Template </h2>

<%= render "form" %>

app/views/emailtemplates/show.html.erb
 <div class='container' style="margin:100px">
      <div class="row">
<h2> Email Template ( <%= @emailtemplate.key %> ) </h2>

  
  <div class="form-group">
    <label for="exampleInputEmail1">
        User name:
    </label>
    
    <%= @emailtemplate.subject %>
  
  </div>
  
    <div class="form-group">
    <label for="exampleInputEmail1">
       Body:
    </label>
    
    <%= @emailtemplate.body %>
  
  </div>
  
  <div>
    <%= link_to 'edit' ,  edit_emailtemplate_path(@emailtemplate.id) %>
    <%= link_to 'destroy', emailtemplate_path(@emailtemplate.id) , method: :delete , data: {confirm: "are you sure you want to delete ?"} %>
    <%= link_to 'all' , emailtemplates_path %>
  </div>
  

app/views/home_page/index.html.erb
<div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
  
   
  
  <title>LearnApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" 
  integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" 
  integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Learning application</a>
            <%= render "shared/menu" %>
        </div>
      
        
      </div>
    </nav>

 <div>
      <%= yield %>
</div>

   


    </div> 

      
</body>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>

<div class="form-group">
    <label for="exampleInputEmail1">
        <%= f.label :patient_name %>
    </label>
        <%= f.text_field :patient_name , class:'form-control',placeholder:'Patient name'%>
</div>    

<div class="form-group">
    <label for="exampleInputEmail1">
        <%= f.label :age %>
    </label>
        <%= f.number_field :age , class: 'form-control', placeholder: 'Age' %>
</div>  

<div class="form-group">
    <label for="exampleInputEmail1">
        <%= f.label :telephone_number %>
    </label>
        <%= f.telephone_field :telephone_number , class: 'form-control' , placeholder: 'Telephone number' %>
</div>  

<%= f.submit 'Submit' , class: 'btn btn-default'%>
<%end%>

app/views/patients/edit.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> Edit Patient <%=@patient.patient_name %> </h2>

<%= render 'form' %>

app/views/patients/index.html.erb
<div class='container' style="margin:100px">
<div style='margin-left:1000px!important'>
<%= link_to 'Add New + ' , new_patient_path %> 
<br\>
</div>

<% @allpatients.each do |patient| %>
Patient name:
<%= link_to patient.patient_name , patient   %> <br/>
Age:
<%= patient.age %><br/>
Telephone number:
<%= patient.telephone_number %><br/>
Creation date: 
<%= patient.created_at %>

<br/>
<%= link_to 'edit' , edit_patient_path(patient.id)%>
<%= link_to 'destroy', patient_path(patient.id) , method: :delete , data: {confirm: "are you sure you want to delete this patient with all appointments ?"} %>
<hr/>
<%end%>

app/views/patients/new.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> New Patient </h2>

<%= render 'form' %>

app/views/patients/show.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> Patient Record ( <%=  @patient.patient_name %> ) </h2>

Age: <%= @patient.age %> <br/>

Telephone number: <%= @patient.telephone_number %> <br/>

<h3>
    Patient appointments
</h3>

<br/>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Add Appointment</button>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
     <div style="padding:30px">
      <h4>
            Add Appointment
       </h4>
       <div>
            <%= form_for ([@patient, @patient.appointments.build]) do |f| %>
                <div class="form-group">
                    <label for="exampleInputEmail1">
                        <%= f.label :start_date %>
                        <%= f.date_field :start_date , class:'form-control',placeholder:'Start date'%>
                </div> 
                
                 <div class="form-group">
                    <label for="exampleInputEmail1">
                        <%= f.label :end_date %>
                        <%= f.date_field :end_date , class:'form-control',placeholder:'End date'%>
                </div>
                
                <div class="form-group">
                    <label for="exampleInputEmail1">
                        <%= f.label :physician %>
                        <%= select_tag 'physicians' , options_from_collection_for_select(@physicians , 'id','physician_name') , class: 'form-control' , placeholder:'select physician'%>
                </div>
                    <%= f.submit 'Submit' , class: 'btn btn-default'%>
            <% end %>
       </div>
      </div> 
    </div>
  </div>
</div>

<div style="padding-top:40px">
<table width="80%">

<th>
    <tr>
        <td>
            Start date
        </td>
        <td>
            End date
        </td>
        <td>
            Physician
        </td>  
        <td>
        </td>      
    </tr>
</th>
<% @patient.appointments.each do |appointment| %>

    <tr>
        <td width="20%">
            <%= appointment.start_date %>       
        </td>
        <td  width="20%">
            <%= appointment.end_date %>
        </td>
        <td width="20%">
        <% if (!appointment.physician.nil?) %>
          <%=  appointment.physician.physician_name %>
        
        </td>
         <td width="20%">
             <%= link_to 'cancel appointment' ,  ([@patient , appointment]) , method: :delete , data: {confirm:"are you sure you want to cancel this appointment ?"} %>
        </td>          
    </tr>
<% end %>
<% end %>
</table>
</div>

app/views/physicians/_form.html.erb
<%= form_for @physician do |f| %>
    <%= f.label :physician_name  %>
    <%= f.text_field :physician_name , class: 'form-control' , placeholder: 'physician name' %> <br/>
    <%= f.label :telephone_number %>
    <%= f.text_field :telephone_number , class: 'form-control' , placeholder: 'telephone number' %>
    <br/>
    <%= f.submit 'Submit' , class: 'btn btn-default'%>
    <hr/>
<% end %>

app/views/physicians/edit.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> Edit Physician <%=@physician.physician_name %> </h2>

<%= render 'form' %>

app/views/physicians/index.html.erb
<div class='container' style="margin:100px">
<div style='margin-left:1000px!important'>
<%= link_to 'Add New + ' , new_physician_path %> 
<br\>
</div>

<% @allphysicians.each do |physician| %>
Physician name:
<%= link_to physician.physician_name , physician %> <br/>
Telephone number:
<%= physician.telephone_number %><br/>
Creation date: 
<%= physician.created_at %>

<br/>
<%= link_to 'edit' , edit_physician_path(physician.id)%>
<%= link_to 'destroy', physician_path(physician.id) , method: :delete , data: {confirm: "are you sure you want to delete this physician with all appointments ?"} %>
<hr/>
<%end%>

app/views/physicians/new.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> New Physician Account </h2>

<%= render "form" %>

</div>

app/views/physicians/show.html.erb
<div class='container' style="margin:100px">
      <div class="row">
<h2> Physician Record</h2>

Physician name: <%= @physician.physician_name %>
<br/>

Telephone number: <%= @physician.telephone_number %> <br/>
<br/>
 <h4>
   My Appointments
 </h4>
<div style="padding-top:20px">
<table width="60%">

<th>
    <tr>
        <td>
            Start date
        </td>
        <td>
            End date
        </td>
        <td>
            Patient name
        </td>    
    </tr>
</th>
<% @physician.appointments.each do |appointment| %>
    <tr>
        <td width="20%">
            <%= appointment.start_date %>       
        </td>
        <td  width="20%">
            <%= appointment.end_date %>
        </td>
        <td width="20%">
             <%= appointment.patient.patient_name %>
        </td>        
    </tr>
<% end %>
</table>
</div>

app/views/shared/_menu.html.erb
<%= link_to 'Patients' , patients_path ,  class: 'navbar-brand' %>
<%= link_to 'Physicians' , physicians_path ,  class: 'navbar-brand' %>
<%= link_to 'Email templates' , emailtemplates_path ,  class: 'navbar-brand' %>

    